### ISSUE TITLE
Can't install .deb, run .so or compile from source

### ISSUE THREAD

**Issue by Jhynjhiruu** [clementgallet/libTAS#30]
When I try and install the 1.1.0 .deb file (or the 1.0.0 .deb file), I get an error:
`Error: Dependency is not satisfiable: libavcodec57 (>=7:3.2.8)|libavcodec-extra57 (>=7:3.2.8)`
This is on Ubuntu 16.04 installing with gdebi (software install just fails, no error details).
Compiling from source (using the instructions in the readme) produces a string of errors and crashes right after `[ 11%] Buildinf CXX object CMakeFiles/linTas.dir/src/linTAS/ui/MainWindow.cpp.o`
Downloading the .tar.gz files seems fine, but nothing at all happens when trying to run the included linTAS file or the libTAS.so file. Running `./linTAS` from terminal produces another error:
`./linTAS: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.22' not found (required by ./linTAS)`.
What should I do? There are a couple of games I really want to TAS...
Before the first releases, I compiled it from source and it ran fine, not usable at that early stage, it was only when I updated to the latest version that it stopped working. I've tried deleting everything and redownloading, I've restarted my computer...

**Comment by NarryG** [comment]
I've been fighting with this. Turns out libavcodec57 isn't available on Ubuntu 16.04. It's available on Ubuntu 17.10.1. You could probably build ffmpeg and libavcodec57 if you fight hard enough, but I just set up a 17.10.1 vm

**Comment by Jhynjhiruu** [comment]
I guess I could just update to 17.10.1, I feel like that would make other things easier too

**Comment by clementgallet** [comment]
As NarrG said, you need a recent version of ffmpeg that isn't available in Ubuntu 16.04. Also, you need Qt5 with at least version 5.6, and Ubuntu 16.04 is shipped with 5.5 (maybe this was the cause of the crash when compiling?). So yeah, the easiest way would be to update to 17.10. This should be resolved when the new LTS version 18.04 will be released.

I should indicate this on the Readme, because most users are using Ubuntu.

**Comment by Jhynjhiruu** [comment]
OK, I've updated to 17.10 and it's installing fine. Building from source still doesn't work though, and I need it compiled for 32 bit for a game I'm trying to TAS (the 64-bit version of this game crashes when opened in linTAS, so I'm trying the 32-bit version)

**Comment by NarryG** [comment]
What's the error you're getting when building?

Building the 32 bit version was an absolute hassle.  Once I got all the dependencies set up, I found that QT doesn't like to serve the 32 bit libraries to cmake on a 64 bit system.  I actually gave up fighting with it, spun up a 32bit vm, and compiled it there.

**Comment by clementgallet** [comment]
I think I will just drop the cross-compiling stuff and advise to get a 32-bit system/VM to run 32-bit games, this has been problematic for too many people.
If the 64-bit version crashed, there is little chance that the 32-bit version will work. You could post an issue about the crash here.

**Comment by clementgallet** [comment]
I added the requirement for Qt version in the CMake file, and advised use a virtual machine instead of trying to cross-compile (8f3348b0d1cbfcc42abd8c704c109d47fd0b50ed).
